name: weinkeller
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.0.2
  font_awesome_flutter: ^10.4.0
  http: 1.3.0
  intl: 0.20.2
  path_provider: ^2.0.11
  provider: ^6.1.2
  qr_code_scanner: ^1.0.1
  shared_preferences: 2.4.0
  sqflite: ^2.0.2+1
  url_launcher: ^6.1.7

dev_dependencies:
  flutter_launcher_icons: ^0.14.2
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/background/weinkeller.jpg
  fonts:
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SFProDisplay-Regular.otf
        - asset: assets/fonts/SFProDisplay-Bold.otf
          weight: 700
        - asset: assets/fonts/SFProDisplay-Italic.otf
          style: italic


flutter_launcher_icons:
  ios: true
  android: true
  image_path_ios: "assets/app-icon.png"
  image_path_ios_dark_transparent: "assets/app-icon-transparent.png"
  image_path_android: "assets/app-icon-android.png"
  adaptive_icon_foreground: "assets/app-icon-foreground.png"
  adaptive_icon_background: "#FFFFFF" # Set the background color to white
  remove_alpha_ios: true
