name: weinkeller
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  url_launcher: ^6.1.7
  camera: ^0.10.0+2 
  font_awesome_flutter: ^10.4.0

  provider: ^6.1.2
  http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path_ios: "assets/Weinkeller_white.png"
  image_path_ios_dark_transparent: "assets/Weinkeller_transparent.png"
  image_path_android: "assets/Weinkeller_white.png"
  adaptive_icon_background: "assets/Weinkeller_white.png"
  adaptive_icon_foreground: "assets/Weinkeller_transparent.png"
  remove_alpha_ios: true