name: weinkeller
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  url_launcher: ^6.1.7
  font_awesome_flutter: ^10.4.0
  shared_preferences: ^2.1.1
  qr_code_scanner: ^1.0.1
  provider: ^6.1.2
  http: ^1.2.2
  flutter_secure_storage: ^9.0.2
  sqflite: ^2.0.2+1
  path_provider: ^2.0.11
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.2

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path_ios: "assets/Weinkeller_white.png"
  image_path_ios_dark_transparent: "assets/Weinkeller_transparent.png"
  image_path_android: "assets/Weinkeller_white.png"
  adaptive_icon_background: "assets/Weinkeller_white.png"
  adaptive_icon_foreground: "assets/Weinkeller_transparent.png"
  remove_alpha_ios: true